name: Take screenshot
on:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Take Screenshot of Google
        uses: sushantmimani/hosted-screenshot@v2
        with:
          url: 'https://google.com'
          path: 'screenshots/'

      - name: Upload Screenshots as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: webpage-screenshots
          path: 'screenshots/'
          retention-days: 30

      - name: Test Deployed Website
        uses: actions/setup-node@v4
        with:
          node-version: '24'
