name: Take screenshot
on:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install -D @playwright/test

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Take Screenshot
        run: node scripts/screenshot.js

      - name: Upload Screenshots as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: webpage-screenshots
          path: 'screenshots/'
          retention-days: 30
